# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.shipment.index:
    path: /index
    defaults:
        _controller: 'shipment.controller.admin:indexAction'
    options:
        require_admin_permission: shipment.index

admin.shipment.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'shipment.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: shipment.index

admin.shipment.add:
    path: /add/{courier}/{orderId}
    defaults:
        _controller: 'shipment.controller.admin:addAction'
    options:
        require_admin_permission: shipment.add

admin.shipment.download_labels:
    path: /labels/{courier}/{date}
    defaults:
        _controller: 'shipment.controller.admin:downloadLabelsAction'
    options:
        require_admin_permission: shipment.index

admin.shipment.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'shipment.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: shipment.edit

admin.shipment.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'shipment.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: shipment.delete

admin.shipment.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'shipment.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: shipment.delete

admin.shipment.print:
    path: /print/{guid}
    defaults:
        _controller: 'shipment.controller.admin:printAction'
    options:
        require_admin_permission: shipment.index
